version: '3.9'

services:
  main_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python main.py"
    ports:
      - "8090:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python consumer.py"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: aaman007
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .db:/var/lib/mysql
    ports:
      - "33067:3306"
